# Site settings
title: Mobile Design Class
email: mak@makzan.net
description: > # this means to ignore newlines until "baseurl:"
  This is a class by Makzan about building mobile website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mobiledesignclass.com" # the base hostname & protocol for your site
twitter_username: makzan
github_username:  makzan

# Build settings
markdown: kramdown
